export const langObj = {
    RU: {
        priority: 'Приоритет',
        low: 'Низкий',
        medium: 'Средний',
        high: 'Высокий',
        addtask: 'Добавить',
        edittask: 'Изменить',
        theme: 'Тема',
        logout: 'Выйти',
        language: 'Язык',
        todo: 'В работе',
        completed: 'Выполнено',
        hello: 'Привет',
        title: 'Заголовок',
        text: 'Текст',
        close: 'Закрыть',
        edit: 'Изменить',
        complete: 'Выполнить',
        delete: 'Удалить',
        inputErrMsg: 'Это поле обязательно для заполнения',
        email: 'Электронная почта',
        password: 'Пароль',
        inputPassword: 'Введите ваш пароль',
        enter: 'Войти в список задач',
        signin: 'Войти',
        signup: 'Зарегистрироваться',
        emailErrMsg: 'Пользователь с таким адресом не найден',
        passwordErrMsg: 'Неправильный пароль',
        name: 'Имя',
        inputName: 'Введите ваше имя',
        surname: 'Фамилия',
        inputSurname: 'Введите вашу фамилию',
        login: 'Логин',
        inputLogin: 'Введите ваш логин',
        repeatedPassword: 'Повторите пароль',
        inputRepeatedPassword: 'Повторите ваш пароль',
        signUpToDo: 'Зарегистрироваться в списке задач',
        back: 'Назад',
        passwordCheckGood: 'Пароли совпадают',
        passwordCheckErrMsg: 'Пароли не совпадают',
        loginMatchErrMsg: 'Пользователь с таким логином уже зарегистрирован',
        emailMatchErrMsg: 'Пользователь с таким адресом уже зарегистрирован',
        emailIncErrMsg: 'Введен некорректный адрес',
        emailGood: 'Вы можете использовать данный адрес',
        loginGood: 'Вы можете использовать данный логин',
        passwordIncorrect: 'Пароль должен содержать минимум 8 символов латинского алфавита, в т.ч. не менее 1 заглавной и прописной буквы, 1 цифры и 1 спецсимвола',
        passwordCorrect: 'Вы можете использовать данный пароль'
    },
    EN: {
        priority: 'Priority',
        low: 'Low',
        medium: 'Medium',
        high: 'High',
        addtask: 'Add task',
        edittask: 'Edit task',
        theme: 'Theme',
        logout: 'Logout',
        language: 'Language',
        todo: 'ToDo',
        completed: 'Completed',
        hello: 'Hello',
        title: 'Title',
        text: 'Text',
        close: 'Close',
        edit: 'Edit',
        complete: 'Complete',
        delete: 'Delete',
        inputErrMsg: 'This field is required',
        email: 'Email',
        password: 'Password',
        inputPassword: 'Enter your password',
        enter: 'Enter ToDoList',
        signin: 'Sign in',
        signup: 'Sign up',
        emailErrMsg: 'User with this email was not found',
        passwordErrMsg: 'Incorrect password',
        name: 'Name',
        inputName: 'Enter your name',
        surname: 'Second name',
        inputSurname: 'Enter your second name',
        login: 'Login',
        inputLogin: 'Enter your login',
        signUpToDo: 'Sign up ToDoList',
        repeatedPassword: 'Repeat password',
        inputRepeatedPassword: 'Repeat your password',
        back: 'Back',
        passwordCheckGood: 'Passwords match',
        passwordCheckErrMsg: 'Passwords do not match',
        loginMatchErrMsg: 'User with this login is already registered',
        emailMatchErrMsg: 'User with this email is already registered',
        emailIncErrMsg: 'Email entered is incorrect',
        emailGood: 'You can use the email',
        loginGood: 'You can use this login',
        passwordIncorrect: 'The password must contain at least 8 characters, incl. at least 1 uppercase and lowercase letters of the Latin alphabet, 1 number and 1 special character',
        passwordCorrect: 'You can use this password'
    }
};